version: '3'
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - "discovery.type=single-node"
     - "script.painless.regex.enabled=true"
     - "xpack.security.enabled=false"
  web:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile_web
      # If you are behind a proxy, you must uncomment
      # the next 3 lines
      # args:
      #  - http_proxy
      #  - https_proxy
    ports:
     - "127.0.0.1:8000:8000"
    # If you are behind a proxy, you must set the
    # proxy settings here (uncomment the next 4 lines)
    # environment:
    #  - "http_proxy=http://proxy.example:80"
    #  - "https_proxy=http://proxy.example:80"
    #  - "no_proxy=localhost,127.0.0.1"
  api:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile_api
      # If you are behind a proxy, you must uncomment
      # the next 3 lines
      # args:
      #  - http_proxy
      #  - https_proxy
    ports:
     - "127.0.0.1:8080:8080"
    # If you are behind a proxy, you must set the
    # proxy settings here (uncomment the next 4 lines)
    # environment:
    #  - "http_proxy=http://proxy.example:80"
    #  - "https_proxy=http://proxy.example:80"
    #  - "no_proxy=localhost,127.0.0.1"
    depends_on:
     - elastic
