FROM python:3.6
MAINTAINER Austin West awest1339

ENV PYTHON_VER 3.6.2

COPY . /opt/multiscanner
COPY ./docker_utils/*.ini /opt/multiscanner/

WORKDIR /opt/multiscanner
RUN ./install.sh

RUN pip install .

# Run script
# The sleep is a workaround to make extra sure that
# the ElasticSearch container is up before the api
# attempts to connect to it
CMD sleep 30; multiscanner-api
