FROM python:3.6
MAINTAINER Austin West awest1339

ENV PYTHON_VER 3.6.2

COPY . /opt/multiscanner
COPY ./docker_utils/*.ini /opt/multiscanner/
# Commented until ember module problems are resolved
# COPY ./etc/ember_model_2017.txt /opt/multiscanner/etc/ember/

WORKDIR /opt/multiscanner
RUN ./install.sh

# Run script
CMD multiscanner-web
